.PHONY: clean All

All:
	@echo "----------Building project:[ Personal_tests - Debug ]----------"
	@cd "Personal_tests" && "$(MAKE)" -f  "Personal_tests.mk"
clean:
	@echo "----------Cleaning project:[ Personal_tests - Debug ]----------"
	@cd "Personal_tests" && "$(MAKE)" -f  "Personal_tests.mk" clean
