.PHONY: clean All

All:
	@echo "----------Building project:[ varables_constants - Debug ]----------"
	@cd "varables_constants" && "$(MAKE)" -f  "varables_constants.mk"
clean:
	@echo "----------Cleaning project:[ varables_constants - Debug ]----------"
	@cd "varables_constants" && "$(MAKE)" -f  "varables_constants.mk" clean
