.PHONY: clean All

All:
	@echo "----------Building project:[ Account - Debug ]----------"
	@cd "Account" && "$(MAKE)" -f  "Account.mk"
clean:
	@echo "----------Cleaning project:[ Account - Debug ]----------"
	@cd "Account" && "$(MAKE)" -f  "Account.mk" clean
