.PHONY: clean All

All:
	@echo "----------Building project:[ virtual_methods - Debug ]----------"
	@cd "Section15" && "$(MAKE)" -f  "virtual_methods.mk"
clean:
	@echo "----------Cleaning project:[ virtual_methods - Debug ]----------"
	@cd "Section15" && "$(MAKE)" -f  "virtual_methods.mk" clean
