.PHONY: clean All

All:
	@echo "----------Building project:[ c++_Class_Training - Debug ]----------"
	@cd "C:\Users\25479\Documents\Search Data\c++ training\c++_Class_Training\c++_Class_Training" && "$(MAKE)" -f  "c++_Class_Training.mk"
clean:
	@echo "----------Cleaning project:[ c++_Class_Training - Debug ]----------"
	@cd "C:\Users\25479\Documents\Search Data\c++ training\c++_Class_Training\c++_Class_Training" && "$(MAKE)" -f  "c++_Class_Training.mk" clean
